# Generated by Django 4.2.1 on 2024-08-26 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=255, verbose_name='name_uz')),
                ('name_ru', models.CharField(max_length=255, verbose_name='name_ru')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CakeApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=255, verbose_name='name')),
                ('cake_weight', models.IntegerField(verbose_name='Tort-massasi')),
                ('fillings', models.CharField(max_length=250, verbose_name='fillings')),
                ('number_persons', models.IntegerField(verbose_name='odam_soni')),
                ('price', models.IntegerField(verbose_name='tort-narxi')),
                ('small_info', models.TextField(max_length=252, verbose_name='samall-info')),
                ('telephone_number', models.IntegerField(verbose_name='telefon-nomer')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category_uz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='Kategoriya_uz')),
            ],
        ),
    ]
