# Generated by Django 4.2.1 on 2024-08-26 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cakeapi_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CakeApi',
            new_name='ApiCakes',
        ),
    ]
